### ISSUE TITLE
Only first line parsed?

### ISSUE THREAD

**Issue by aroesler-privat** [F-i-f/ssh-search-provider#3]
Hi,

I am not able to ssh to one ofthe hosts I defined in .ssh/config & .ssh/known_hosts. The files are available for download here:
[sshdebug.tar.gz](https://github.com/F-i-f/ssh-search-provider/files/3052028/sshdebug.tar.gz)

When searching for zabbix or chiaraguin nothing is found. When searching for andreas@ or root@ I get 'andreas@object:undefined' or 'root@object:undefined'. 

What I tried so far is:
* watching logfile via: journalctl -f
* when searching I get:
> JS ERROR: Exception in callback for signal: activate: ReferenceError: substr is not defined
> activateResult@/home/andreas/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org/extension.js:252:13

This seems not to be the reason. I tried as well:
* adding `global.log('[SshSearchProvider]',content);;` after ...load_content in _onConfigChanged and _parseKnownHosts 
* watching logfile only give me the first lines of both files

But I am not an expert in JS at all - so its not unlikely I missed the main part ;-).

I am running:
* Ubuntu 18.04.1
* Shell version: 3.28.3
* Extension version: 3

**Comment by F-i-f** [comment]
There was an issue with the extension when running with gnome-shell 3.28.
Note that the extension only claimed to support 3.30 and 3.32.

Nevertheless, I think I have a fix.
Can you please try the following zip file:
[ssh-search-provider@extensions.gnome-shell.fifi.org-v3-6-g8b71084.zip](https://github.com/F-i-f/ssh-search-provider/files/3052212/ssh-search-provider%40extensions.gnome-shell.fifi.org-v3-6-g8b71084.zip)

Just unzip it under `~/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org` and overwrite the files.

And please report if it works or not.

If it doesn't work, please attach the output of `journalctl -b`.

Thanks.

**Comment by aroesler-privat** [comment]
Great - works like expected. Thanks a lot!

**Comment by F-i-f** [comment]
I have released version 4 which fixes the problem.
It's currently under review by the gnome-shell team.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/ssh-search-provider/) or download [version 4 directly here](https://github.com/F-i-f/ssh-search-provider/releases/download/v4/ssh-search-provider@extensions.gnome-shell.fifi.org.v4.shell-extension.zip).
