### ISSUE TITLE
Gnome-console

### ISSUE THREAD

**Issue by eliohann** [F-i-f/ssh-search-provider#8]
Hi,

I use gnome-console a lot, i love the title bar color feature (purple for ssh connexion, red for root rights for example).
Can you handle it  ?
I cannot find a config that work for it ... when i click a search result, it correctly opens gnome-console, but with no ssh connexion, only as if i open gnome console by myself ...

**Comment by F-i-f** [comment]
The settings are the same as for Gnome Terminal:
- Arguments: `--`
- Pass SSH command line as single argument: false/disabled.

Next version will provide defaults for Gnome Console.

**Comment by F-i-f** [comment]
This has been released in version 16.
